import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

// Pre-translated UI strings for 24 languages
const resources = {
  en: { translation: { "Home": "Home", "My Links": "My Links", "Collections": "Collections", "Favorites": "Favorites", "Explore": "Explore", "Settings": "Settings", "Identity": "Identity", "Save New Link": "Save New Link", "Search": "Search", "Appearance": "Appearance", "Theme": "Theme", "Language": "Language", "Log Out": "Log Out", "LinkVault": "LinkVault", "General": "General", "Data": "Data & Export", "Privacy": "Privacy & Security", "Danger": "Danger Zone", "Save": "Save", "Cancel": "Cancel", "Delete": "Delete", "Edit": "Edit", "Apply Preferences": "Apply Preferences", "Theme Environments": "Theme Environments", "Accent Color": "Accent Color", "Background Identity": "Background Identity" } },
  hi: { translation: { "Home": "मुख्य पृष्ठ", "My Links": "मेरे लिंक", "Collections": "संग्रह", "Favorites": "पसंदीदा", "Explore": "खोजें", "Settings": "सेटिंग्स", "Identity": "पहचान", "Save New Link": "नया लिंक सहेजें", "Search": "खोज", "Appearance": "प्रकटन", "Theme": "थीม", "Language": "भाषा", "Log Out": "लॉग आउट", "LinkVault": "लिंकवॉल्ट", "General": "सामान्य", "Data": "डेटा और निर्यात", "Privacy": "गोपनीयता और सुरक्षा", "Danger": "खतरा क्षेत्र", "Save": "सहेजें", "Cancel": "रद्द करें", "Delete": "हटाएं", "Edit": "संपादित करें", "Apply Preferences": "प्राथमिकताएं लागू करें" } },
  te: { translation: { "Home": "హోమ్", "My Links": "నా లింక్‌లు", "Collections": "సేకరణలు", "Favorites": "ఇష్టమైనవి", "Explore": "అన్వేషించండి", "Settings": "సెట్టింగ్‌లు", "Identity": "గుర్తింపు", "Save New Link": "కొత్త లింక్‌ను సేవ్ చేయండి", "Search": "శోధన", "Appearance": "కనిపించే విధానం", "Theme": "థీమ్", "Language": "భాష", "Log Out": "లాగౌట్", "LinkVault": "లింక్‌వాల్ట్", "General": "సాధారణ", "Data": "డేటా & ఎగుమతి", "Privacy": "గోపన్యత & భద్రత", "Danger": "ప్రమాద ప్రాంతం", "Save": "సేవ్", "Cancel": "రద్దు", "Delete": "తొలగించు", "Edit": "సవరించు", "Apply Preferences": "ప్రాధాన్యతలను వర్తింపజేయండి" } },
  ta: { translation: { "Home": "முகப்பு", "My Links": "என் இணைப்புகள்", "Collections": "தொகுப்புகள்", "Favorites": "பிடித்தவை", "Explore": "ஆராயுங்கள்", "Settings": "அமைப்புகள்", "Identity": "அடையாளம்", "Save New Link": "புதிய இணைப்பை சேமி", "Search": "தேடல்", "Appearance": "தோற்றம்", "Theme": "தீம்", "Language": "மொழி", "Log Out": "வெளியேறு", "LinkVault": "லிங்க்வால்ட்", "General": "பொதுவான", "Data": "தரவு மற்றும் ஏற்றுமதி", "Privacy": "தனியுரிமை மற்றும் பாதுகாப்பு", "Danger": "அபாய பகுதி", "Save": "சேமி", "Cancel": "ரத்து", "Delete": "அழி", "Edit": "திருத்து", "Apply Preferences": "விருப்பங்களைப் பயன்படுத்து" } },
  kn: { translation: { "Home": "ಮುಖಪುಟ", "My Links": "ನನ್ನ ಲಿಂಕ್‌ಗಳು", "Collections": "ಸಂಗ್ರహಗಳು", "Favorites": "ಮೆಚ್ಚಿನವುಗಳು", "Explore": "ಅನ್ವೇಷಿಸಿ", "Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", "Identity": "ಗುರುತು", "Save New Link": "ಹೊಸ ಲಿಂಕ್ ಉಳಿಸಿ", "Search": "ಹುಡುಕಾట", "Appearance": "ಗೋಚರತೆ", "Theme": "ಥೀಮ್", "Language": "ಭಾಷೆ", "Log Out": "ಲಾಗ್ ಔಟ್", "LinkVault": "ಲಿಂಕ್‌ವಾಲ್ಟ್", "General": "ಸಾಮಾನ್ಯ", "Data": "ಡೇಟಾ ಮತ್ತು ರಫ್ತು", "Privacy": "ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ", "Danger": "ಅಪಾಯ ವಲಯ", "Save": "ಉಳಿಸು", "Cancel": "ರದ್ದುಮಾಡು", "Delete": "ಅಳಿಸು", "Edit": "ಸಂಪಾದಿಸು", "Apply Preferences": "ಆದ್ಯತೆಗಳನ್ನು ಅನ್ವಯಿಸಿ" } },
  ml: { translation: { "Home": "ഹോം", "My Links": "എന്റെ ലിങ്കുകൾ", "Collections": "ശേഖരങ്ങൾ", "Favorites": "പ്രിയപ്പെട്ടവ", "Explore": "പര്യവേക്ഷണം ചെയ്യുക", "Settings": "സജ്జീകരണങ്ങൾ", "Identity": "തിരിച്ചറിയൽ", "Save New Link": "புതിയ ലിങ്ക് സംരക്ഷിക്കുക", "Search": "തിരയുക", "Appearance": "കാഴ്ച", "Theme": "തീം", "Language": "ഭാష", "Log Out": "ലോഗ് ഔಟ್", "LinkVault": "ಲಿങ്ക്വോൾട്ട്", "General": "പൊതുവായ", "Data": "ഡാറ്റയും കയറ്റുമതിയും", "Privacy": "സ്വകാര്യതയും സുരക്ഷയും", "Danger": "അപകട മേഖല", "Save": "സംരക്ഷിക്കുക", "Cancel": "റദ്ദാക്കുക", "Delete": "നശിപ്പിക്കുക", "Edit": "തിരുത്തുക", "Apply Preferences": "മുൻഗണനകൾ പ്രയോഗിക്കുക" } },
  mr: { translation: { "Home": "मुख्यपृष्ठ", "My Links": "माझ्या लिंक्स", "Collections": "संग्रह", "Favorites": "आवडते", "Explore": "अन्वेषण", "Settings": "सेटिंग्ज", "Identity": "ओळख", "Save New Link": "नवीन लिंक सेव्ह करा", "Search": "शोधा", "Appearance": "देखावा", "Theme": "थीम", "Language": "भाषा", "Log Out": "लॉग आउट", "LinkVault": "लिंकवॉल्ट", "General": "सामान्य", "Data": "डेटा आणि निर्यात", "Privacy": "गोपनीयता आणि सुरक्षा", "Danger": "धोकादायक क्षेत्र", "Save": "जतन करा", "Cancel": "रद करा", "Delete": "काढून टाका", "Edit": "संपादित करा", "Apply Preferences": "प्राधान्ये लागू करा" } },
  bn: { translation: { "Home": "হোম", "My Links": "আমার লিঙ্কগুলি", "Collections": "সংগ্রহ", "Favorites": "পছন্দসই", "Explore": "অন্বেষণ করুন", "Settings": "সেটিংস", "Identity": "পরিচয়", "Save New Link": "নতুন লিঙ্ক সংরক্ষণ করুন", "Search": "অনুসন্ধান", "Appearance": "উপস্থিতি", "Theme": "থিম", "Language": "ভাষা", "Log Out": "লগ আউট", "LinkVault": "লিঙ্কভল্ট", "General": "সাধারণ", "Data": "ডেটা এবং রপ্তানি", "Privacy": "গোপনীয়তা ও নিরাপত্তা", "Danger": "বিপদ অঞ্চল", "Save": "সংরক্ষণ", "Cancel": "বাতিল", "Delete": "মুছে ফেলুন", "Edit": "সম্পাদনা", "Apply Preferences": "পছন্দগুলি প্রয়োগ করুন" } },
  es: { translation: { "Home": "Inicio", "My Links": "Mis Enlaces", "Collections": "Colecciones", "Favorites": "Favoritos", "Explore": "Explorar", "Settings": "Ajustes", "Identity": "Identidad", "Save New Link": "Guardar Nuevo Enlace", "Search": "Buscar", "Appearance": "Apariencia", "Theme": "Tema", "Language": "Idioma", "Log Out": "Cerrar sesión", "LinkVault": "LinkVault", "General": "General", "Data": "Datos y Exportación", "Privacy": "Privacidad y Seguridad", "Danger": "Zona de Peligro", "Save": "Guardar", "Cancel": "Cancelar", "Delete": "Eliminar", "Edit": "Editar", "Apply Preferences": "Aplicar Preferencias" } },
  fr: { translation: { "Home": "Accueil", "My Links": "Mes Liens", "Collections": "Collections", "Favorites": "Favoris", "Explore": "Explorer", "Settings": "Paramètres", "Identity": "Identité", "Save New Link": "Enregistrer Nouveau Lien", "Search": "Recherche", "Appearance": "Apparence", "Theme": "Thème", "Language": "Langue", "Log Out": "Déconnexion", "LinkVault": "LinkVault", "General": "Général", "Data": "Données et Export", "Privacy": "Confidentialité et Sécurité", "Danger": "Zone de Danger", "Save": "Enregistrer", "Cancel": "Annuler", "Delete": "Supprimer", "Edit": "Modifier", "Apply Preferences": "Appliquer les Préférences" } },
  de: { translation: { "Home": "Startseite", "My Links": "Meine Links", "Collections": "Sammlungen", "Favorites": "Favoriten", "Explore": "Erkunden", "Settings": "Einstellungen", "Identity": "Identität", "Save New Link": "Neuen Link speichern", "Search": "Suche", "Appearance": "Erscheinungsbild", "Theme": "Theme", "Language": "Sprache", "Log Out": "Abmelden", "LinkVault": "LinkVault", "General": "Allgemein", "Data": "Daten & Export", "Privacy": "Datenschutz & Sicherheit", "Danger": "Gefahrenzone", "Save": "Speichern", "Cancel": "Abbrechen", "Delete": "Löschen", "Edit": "Bearbeiten", "Apply Preferences": "Einstellungen übernehmen" } },
  it: { translation: { "Home": "Home", "My Links": "I Miei Link", "Collections": "Collezioni", "Favorites": "Preferiti", "Explore": "Esplora", "Settings": "Impostazioni", "Identity": "Identità", "Save New Link": "Salva Nuovo Link", "Search": "Cerca", "Appearance": "Aspetto", "Theme": "Tema", "Language": "Lingua", "Log Out": "Esci", "LinkVault": "LinkVault", "General": "Generale", "Data": "Dati ed Esportazione", "Privacy": "Privacy e Sicurezza", "Danger": "Zona di Pericolo", "Save": "Salva", "Cancel": "Annulla", "Delete": "Elimina", "Edit": "Modifica", "Apply Preferences": "Applica Preferenze" } },
  pt: { translation: { "Home": "Início", "My Links": "Meus Links", "Collections": "Coleções", "Favorites": "Favoritos", "Explore": "Explorar", "Settings": "Configurações", "Identity": "Identidade", "Save New Link": "Salvar Novo Link", "Search": "Buscar", "Appearance": "Aparência", "Theme": "Tema", "Language": "Idioma", "Log Out": "Sair", "LinkVault": "LinkVault", "General": "Geral", "Data": "Dados e Exportação", "Privacy": "Privacidade e Segurança", "Danger": "Zona de Perigo", "Save": "Salvar", "Cancel": "Cancelar", "Delete": "Excluir", "Edit": "Editar", "Apply Preferences": "Aplicar Preferências" } },
  nl: { translation: { "Home": "Home", "My Links": "Mijn Links", "Collections": "Collecties", "Favorites": "Favorieten", "Explore": "Ontdekken", "Settings": "Instellingen", "Identity": "Identiteit", "Save New Link": "Nieuwe Link Opslaan", "Search": "Zoeken", "Appearance": "Uiterlijk", "Theme": "Thema", "Language": "Taal", "Log Out": "Uitloggen", "LinkVault": "LinkVault", "General": "Algemeen", "Data": "Gegevens & Export", "Privacy": "Privacy & Beveiliging", "Danger": "Gevarenzone", "Save": "Opslaan", "Cancel": "Annuleren", "Delete": "Verwijderen", "Edit": "Bewerken", "Apply Preferences": "Voorkeuren Toepassen" } },
  ru: { translation: { "Home": "Главная", "My Links": "Мои ссылки", "Collections": "Коллекции", "Favorites": "Избранное", "Explore": "Исследовать", "Settings": "Настройки", "Identity": "Личность", "Save New Link": "Сохранить новую ссылку", "Search": "Поиск", "Appearance": "Внешний вид", "Theme": "Тема", "Language": "Язык", "Log Out": "Выйти", "LinkVault": "LinkVault", "General": "Общие", "Data": "Данные и Экспорт", "Privacy": "Приватность и Безопасность", "Danger": "Опасная зона", "Save": "Сохранить", "Cancel": "Отмена", "Delete": "Удалить", "Edit": "Редактировать", "Apply Preferences": "Применить настройки" } },
  ja: { translation: { "Home": "ホーム", "My Links": "マイリンク", "Collections": "コレクション", "Favorites": "お気に入り", "Explore": "探索", "Settings": "設定", "Identity": "アイデンティティ", "Save New Link": "新しいリンクを保存", "Search": "検索", "Appearance": "外観", "Theme": "テーマ", "Language": "言語", "Log Out": "ログアウト", "LinkVault": "リンクボールト", "General": "一般", "Data": "データとエクスポート", "Privacy": "プライバシーとセキュリティ", "Danger": "危険ゾーン", "Save": "保存", "Cancel": "キャンセル", "Delete": "削除", "Edit": "編集", "Apply Preferences": "設定を適用" } },
  ko: { translation: { "Home": "홈", "My Links": "내 링크", "Collections": "컬렉션", "Favorites": "즐겨찾기", "Explore": "탐색", "Settings": "설정", "Identity": "신원", "Save New Link": "새 링크 저장", "Search": "검색", "Appearance": "외관", "Theme": "테마", "Language": "언어", "Log Out": "로그아웃", "LinkVault": "링크볼트", "General": "일반", "Data": "데이터 및 내보내기", "Privacy": "개인정보 및 보안", "Danger": "위험 구역", "Save": "저장", "Cancel": "취소", "Delete": "삭제", "Edit": "편집", "Apply Preferences": "설정 적용" } },
  zh: { translation: { "Home": "首页", "My Links": "我的链接", "Collections": "收藏夹", "Favorites": "最爱", "Explore": "探索", "Settings": "设置", "Identity": "身份", "Save New Link": "保存新链接", "Search": "搜索", "Appearance": "外观", "Theme": "主题", "Language": "语言", "Log Out": "登出", "LinkVault": "链接金库", "General": "常规", "Data": "数据与导出", "Privacy": "隐私与安全", "Danger": "危险区域", "Save": "保存", "Cancel": "取消", "Delete": "删除", "Edit": "编辑", "Apply Preferences": "应用首选项" } },
  ar: { translation: { "Home": "الرئيسية", "My Links": "روابطي", "Collections": "المجموعات", "Favorites": "المفضلة", "Explore": "استكشف", "Settings": "الإعدادات", "Identity": "الهوية", "Save New Link": "حفظ رابط جديد", "Search": "بحث", "Appearance": "المظهر", "Theme": "السمة", "Language": "اللغة", "Log Out": "تسجيل خروج", "LinkVault": "لينك فولت", "General": "عام", "Data": "البيانات والتصدير", "Privacy": "الخصوصية والأمان", "Danger": "منطقة الخطر", "Save": "حفظ", "Cancel": "إلغاء", "Delete": "حذف", "Edit": "تعديل", "Apply Preferences": "تطبيق التفضيلات" } },
  tr: { translation: { "Home": "Ana Sayfa", "My Links": "Bağlantılarım", "Collections": "Koleksiyonlar", "Favorites": "Favoriler", "Explore": "Keşfet", "Settings": "Ayarlar", "Identity": "Kimlik", "Save New Link": "Yeni Bağlantı Kaydet", "Search": "Arama", "Appearance": "Görünüm", "Theme": "Tema", "Language": "Dil", "Log Out": "Çıkış Yap", "LinkVault": "LinkVault", "General": "Genel", "Data": "Veri ve Dışa Aktarma", "Privacy": "Gizlilik ve Güvenlik", "Danger": "Tehlikeli Bölge", "Save": "Kaydet", "Cancel": "İptal", "Delete": "Sil", "Edit": "Düzenle", "Apply Preferences": "Tercihleri Uygula" } },
  id: { translation: { "Home": "Beranda", "My Links": "Tautan Saya", "Collections": "Koleksi", "Favorites": "Favorit", "Explore": "Jelajahi", "Settings": "Pengaturan", "Identity": "Identitas", "Save New Link": "Simpan Tautan Baru", "Search": "Cari", "Appearance": "Tampilan", "Theme": "Tema", "Language": "Bahasa", "Log Out": "Keluar", "LinkVault": "LinkVault", "General": "Umum", "Data": "Data & Ekspor", "Privacy": "Privasi & Keamanan", "Danger": "Zona Bahaya", "Save": "Simpan", "Cancel": "Batal", "Delete": "Hapus", "Edit": "Edit", "Apply Preferences": "Terapkan Preferensi" } },
  th: { translation: { "Home": "หน้าหลัก", "My Links": "ลิงก์ของฉัน", "Collections": "คอลเลกชัน", "Favorites": "รายการโปรด", "Explore": "สำรวจ", "Settings": "การตั้งค่า", "Identity": "ข้อมูลส่วนตัว", "Save New Link": "บันทึกลิงก์ใหม่", "Search": "ค้นหา", "Appearance": "ลักษณะที่ปรากฏ", "Theme": "ธีม", "Language": "ภาษา", "Log Out": "ออกจากระบบ", "LinkVault": "LinkVault", "General": "ทั่วไป", "Data": "ข้อมูลและการส่งออก", "Privacy": "ความเป็นส่วนตัวและความปลอดภัย", "Danger": "เขตอันตราย", "Save": "บันทึก", "Cancel": "ยกเลิก", "Delete": "ลบ", "Edit": "แก้ไข", "Apply Preferences": "ใช้การตั้งค่า" } },
  vi: { translation: { "Home": "Trang chủ", "My Links": "Liên kết của tôi", "Collections": "Bộ sưu tập", "Favorites": "Yêu thích", "Explore": "Khám phá", "Settings": "Cài đặt", "Identity": "Danh tính", "Save New Link": "Lưu liên kết mới", "Search": "Tìm kiếm", "Appearance": "Giao diện", "Theme": "Chủ đề", "Language": "Ngôn ngữ", "Log Out": "Đăng xuất", "LinkVault": "LinkVault", "General": "Chung", "Data": "Dữ liệu & Xuất", "Privacy": "Quyền riêng tư & Bảo mật", "Danger": "Vùng nguy hiểm", "Save": "Lưu", "Cancel": "Hủy", "Delete": "Xóa", "Edit": "Sửa", "Apply Preferences": "Áp dụng tùy chọn" } },
  sv: { translation: { "Home": "Hem", "My Links": "Mina länkar", "Collections": "Samlingar", "Favorites": "Favoriter", "Explore": "Utforska", "Settings": "Inställningar", "Identity": "Identitet", "Save New Link": "Spara ny länk", "Search": "Sök", "Appearance": "Utseende", "Theme": "Tema", "Language": "Språk", "Log Out": "Logga ut", "LinkVault": "LinkVault", "General": "Allmänt", "Data": "Data & Export", "Privacy": "Integritet & Säkerhet", "Danger": "Farozon", "Save": "Spara", "Cancel": "Avbryt", "Delete": "Radera", "Edit": "Redigera", "Apply Preferences": "Verkställ inställningar" } }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "en",
    interpolation: {
      escapeValue: false, // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
    },
  });

export default i18n;
